fix(dal-test): reduce the default cyclone pool size for tests
This change changes the size of the cyclone pool that are set for *each*
integration test. Prior to this change the value was updated recently to
`50` and this led to issues running the DAL integration test suite on
some larger Linux systems (namely Threadripper workstations with 64 or
128-cores). The test suite issue would manifest as:

```
thread 'main' panicked at third-party/rust/tokio-1.40.0.crate/src/runtime/scheduler/multi_thread/worker.rs:466:13:
OS can't spawn worker thread: Resource temporarily unavailable (os error 11)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

A little misleading in that the number of threads per-process *and* the
number of processes both contribute to this failure.

While the update pool size is considerably smaller, the total runtime
of `lib/dal:test-integration` didn't seem to vary by more than about 5
seconds when runs were attempted with different values.

Signed-off-by: Fletcher Nichol <fletcher@systeminit.com>