fix(buck2): add `@oss-disable` to `@fbsource` code
The `@fbsource` repository is not shipped with the open sourced prelude
and so cannot be found when attempting to load it.

This was discovered via running a BXL script that was running the
following query on files modified in a Git commit range:

```
buck2 uquery 'owner(prelude//apple/tools/bundling/BUCK.v2)'
```

Resulting in the following failure:

```
Traceback (most recent call last):
  File <builtin>, in <module>
  * bxl/dependent_targets.bxl:2, in _dependent_targets_impl
      targets = _compute_targets(ctx)
  * bxl/dependent_targets.bxl:130, in _compute_targets
      modified_targets = _dependent_modified_file_targets(ctx)
  * bxl/dependent_targets.bxl:234, in _dependent_modified_file_targets
      results_set = ctx.uquery().eval(query, query_args = modified_files)
error: Error evaluating expression:
    owner(prelude//apple/tools/bundling/BUCK.v2)
    ^------------------------------------------^

   --> bxl/dependent_targets.bxl:234:19
    |
234 |     results_set = ctx.uquery().eval(query, query_args = modified_files)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |

Error evaluating expression:
    owner(prelude//apple/tools/bundling/BUCK.v2)
    ^------------------------------------------^

Caused by:
    0: From load at prelude/apple/tools/bundling/BUCK.v2:1
    1: From load at prelude/apple/tools/defs.bzl:9
    2: File not found: `none//tools/build_defs/python_platform.bzl`
```

Signed-off-by: Fletcher Nichol <fletcher@systeminit.com>