chore: update Rust dependencies to support 1.53.0
This update is in service of running on the current Rust release.
After running a full clean/build, I saw several errors like this:

```console
error[E0277]: cannot divide `usize` by `u32`
  --> /home/fnichol/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.7.4/src/atof/algorithm/bhcomp.rs:62:22
   |
62 |     let bytes = bits / Limb::BITS;
   |                      ^ no implementation for `usize / u32`
   |
   = help: the trait `Div<u32>` is not implemented for `usize`
```

Our Rust dependencies haven't been bumped in several months and there
wasn't any dramatic updates that broke compilation/tests/basic behavior
(that I saw when lightly using the system).

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>