chore(deps): pin to awscli2 2.13.25 until unstable channel is updated
This change pins the version of `awscli2` back to 2.13.25 as the current
version in the `nixpkgs-unstable` channel fails to install with:

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/j2riph1av209fsm6crlgmbs3a38d875w-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'nix-shell'

         at /nix/store/j2riph1av209fsm6crlgmbs3a38d875w-source/pkgs/stdenv/generic/make-derivation.nix:392:7:

          391|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          392|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          393|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: assertion '((pyproject != null) -> (format == null))' failed

       at /nix/store/j2riph1av209fsm6crlgmbs3a38d875w-source/pkgs/development/interpreters/python/mk-python-derivation.nix:110:1:

          109|
          110| assert (pyproject != null) -> (format == null);
             | ^
          111|
```

Once the fix in NixOS/nixpkgs#268590 is merged into
`NixOS/nixpkgs/nixpkgs-unstable`, then we can drop this version pin.

References: NixOS/nixpkgs#268727
See: https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=awscli2

Signed-off-by: Fletcher Nichol <fletcher@systeminit.com>